In [1]:
import numpy as np
import pandas as pd
import scipy.stats as s
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv(r'F:/data.csv')

In [3]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
data.drop([data.columns[0],data.columns[32]],axis=1,inplace=True)

In [5]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [43]:
labels=np.array(data['diagnosis']).reshape(data['diagnosis'].shape[0],1)

In [44]:
x=np.array(data.iloc[:,1:])

In [45]:
x.shape

(569, 30)

In [46]:
mu=np.mean(x,axis=0)

In [48]:
mu=mu.reshape(-1,mu.shape[0])

In [49]:
mu.shape

(1, 30)

In [50]:
x_dash=x-mu

In [52]:
x_dash.shape

(569, 30)

In [55]:
sigma_hat=(1/data.shape[0])*np.matmul(x_dash.T,x_dash)

In [56]:
sigma_hat.shape

(30, 30)

In [57]:
sigma_hat_decompose=np.linalg.svd(sigma_hat)

In [60]:
len(sigma_hat_decompose)

3

In [71]:
Q=sigma_hat_decompose[0]

In [72]:
lmda=sigma_hat_decompose[1]

In [73]:
lmda

array([4.43002671e+05, 7.29725279e+03, 7.02596776e+02, 5.45526944e+01,
       3.98199123e+01, 2.99930721e+00, 1.81213991e+00, 3.70813899e-01,
       1.55240237e-01, 8.39134846e-02, 3.15534015e-02, 7.48418875e-03,
       3.15610001e-03, 2.15770517e-03, 1.32420744e-03, 6.39144051e-04,
       3.74224474e-04, 2.34756323e-04, 1.84259067e-04, 1.63891523e-04,
       7.79729248e-05, 5.75099161e-05, 3.48559114e-05, 2.83453651e-05,
       1.61179909e-05, 1.24682907e-05, 3.67401338e-06, 2.84289915e-06,
       2.00139207e-06, 7.00763523e-07])

In [74]:
Q_tilda=Q[:,0:15]

In [75]:
Q_tilda.shape

(30, 15)

In [76]:
x_new=np.matmul(x_dash,Q_tilda)

In [77]:
x_new.shape

(569, 15)

In [80]:
new_data=pd.DataFrame(data=x_new)

In [81]:
new_data['diagnosis']=labels

In [82]:
new_data

0           1          2          3          4         5  \
0   -1160.142574 -293.917544  48.578398   8.711975  32.000486 -1.265415   
1   -1269.122443   15.630182 -35.394534 -17.861283  -4.334874  0.225872   
2    -995.793889   39.156743  -1.709753  -4.199340  -0.466529  2.652811   
3     407.180803  -67.380320   8.672848  11.759867   7.115461 -1.299436   
4    -930.341180  189.340742   1.374801  -8.499183   7.613289 -1.021160   
..           ...         ...        ...        ...        ...       ...   
564 -1414.126684  110.222492  40.065944  -6.562240  -5.102856  0.395424   
565 -1045.018854   77.057589   0.036669   4.753245 -12.417863  0.059637   
566  -314.501756   47.553525 -10.442407   9.771881  -6.156213  0.870726   
567 -1124.858115   34.129225 -19.742087  23.660881   3.565133 -4.086390   
568   771.527622  -88.643106  23.889032  -2.547249 -14.717566 -4.418123   

            6         7         8         9        10        11        12  \
0    0.931337 -0.148167 -0.745463  0.589359  0.307804 -0.043452  0.034777   
1   -0.046037 -0.200804  0.485828 -0.084035 -0.080642 -0.033042  0.045485   
2   -0.779745  0.274026  0.173874 -0.186994 -0.279174  0.020464  0.083505   
3   -1.267304  0.060555  0.330639 -0.144155 -0.927471  0.174720  0.282556   
4   -0.335522 -0.289109 -0.036087 -0.138502 -0.042228  0.062721 -0.114247   
..        ...       ...       ...       ...       ...       ...       ...   
564 -0.786751 -0.037082  0.452530 -0.235185 -0.163649 -0.052543 -0.075032   
565  0.449831 -0.509154  0.449986  0.493247 -0.007625 -0.055832 -0.015163   
566 -2.166493  0.442279  0.097398 -0.144667  0.109147 -0.076263 -0.004448   
567 -1.705401  0.359964 -0.385030  0.615467 -0.307166  0.028224  0.060561   
568 -2.815752 -0.030039  0.423451 -0.301439 -0.133353  0.115105 -0.019667   

           13        14 diagnosis  
0   -0.065069  0.012934         M  
1    0.005534 -0.021368         M  
2   -0.024824  0.026887         M  
3   -0.080057 -0.043201         M  
4   -0.002274  0.019548         M  
..        ...       ...       ...  
564  0.015211  0.061390         M  
565 -0.009985 -0.003312         M  
566  0.055285  0.012459         M  
567  0.037742  0.031873         M  
568 -0.013734  0.004134         B  

[569 rows x 16 columns]

In [83]:
new_data[new_data['diagnosis']=='B'].shape

(357, 16)

In [84]:
new_data[new_data['diagnosis']=='M'].shape

(212, 16)

In [85]:
training_data_len=int(0.7*new_data.shape[0])

In [86]:
training_data_len

398

In [87]:
benign_training_data=new_data[new_data['diagnosis']=='B'].iloc[0:training_data_len//2]
malingnant_training_data=new_data[new_data['diagnosis']=='M'].iloc[0:training_data_len//2]

In [88]:
benign_training_data.shape

(199, 16)

In [89]:
malingnant_training_data.shape

(199, 16)

In [90]:
training_data=pd.concat([benign_training_data,malingnant_training_data])

In [91]:
training_data

0           1          2          3         4         5  \
19    191.621045   12.259178  -6.241020  -3.588034  6.692721  0.037497   
20    285.051275   14.557362 -10.177971  -1.483015  5.828780  0.790474   
21    683.583952  -32.576126  15.095343 -12.576780  1.707262 -1.104473   
37    355.877850   61.535566  -6.242785  -4.970090 -3.076071  1.750950   
46    783.838668  -56.826556  13.657869 -10.929661 -7.112941 -2.742609   
..           ...         ...        ...        ...       ...       ...   
499 -1099.486889  112.597421 -27.476067  -0.145937 -2.458353 -1.537728   
501   109.464701   -2.229269   3.854344  10.871600 -3.023712  2.215435   
503 -2166.185165 -108.422615  21.170655  -9.870265  4.600230 -6.029129   
509   -64.596512   50.650874 -13.205191  13.519044 -3.370923  1.640083   
512    81.753871  -65.157008  -2.878240  10.121694  4.231035 -1.561071   

            6         7         8         9        10        11        12  \
19   0.336992  0.159502 -0.013716  0.010386  0.078203 -0.036511 -0.029271   
20   0.080541  0.454472 -0.268240  0.092501  0.032368  0.122332  0.037006   
21  -0.309995 -0.328012 -0.135464 -0.232627 -0.039800  0.013665 -0.016789   
37  -0.091251 -0.511769 -0.102631  1.011803  0.024114 -0.059378 -0.000325   
46  -0.747497  0.247352 -0.345514 -0.233113 -0.080757  0.095598  0.009075   
..        ...       ...       ...       ...       ...       ...       ...   
499  1.274740 -0.224613 -0.469098 -0.102762  0.047910  0.093248 -0.100222   
501  0.365275  0.020654 -0.201790 -0.171657 -0.100881  0.175142  0.032250   
503 -3.231749 -0.385159  0.459618  0.086349  0.186573 -0.070107  0.065125   
509  2.685771 -0.600741 -0.693918 -0.225630  0.032308 -0.042296 -0.018556   
512  0.335364  0.303605 -0.151272 -0.183464  0.011138 -0.013619 -0.058982   

           13        14 diagnosis  
19  -0.039346 -0.017123         B  
20   0.000394 -0.017677         B  
21   0.007654  0.010671         B  
37   0.018064 -0.035210         B  
46  -0.027129 -0.006755         B  
..        ...       ...       ...  
499  0.029009  0.056247         M  
501 -0.029611  0.042311         M  
503  0.036807  0.019955         M  
509  0.033451  0.003069         M  
512 -0.046188  0.004539         M  

[398 rows x 16 columns]

In [92]:
cv_data_len= int(0.2*new_data.shape[0])

In [93]:
cv_data_len

113

In [94]:
benign_remaining_data=new_data[new_data['diagnosis']=='B'].iloc[training_data_len//2:]
malingnant_remaining_data=new_data[new_data['diagnosis']=='M'].iloc[training_data_len//2:]

In [95]:
benign_remaining_data.shape

(158, 16)

In [96]:
malingnant_remaining_data.shape

(13, 16)

In [97]:
remaining_data=pd.concat([benign_remaining_data,malingnant_remaining_data])

In [98]:
remaining_data.shape

(171, 16)

In [99]:
cv_data=remaining_data.iloc[0:cv_data_len]
testing_data=remaining_data.iloc[cv_data_len:]

In [100]:
testing_data.shape

(58, 16)

In [105]:
mu_hat_m=np.array(training_data[training_data['diagnosis']=='M'].iloc[:,0:15].mean())
sigma_hat_m=np.array(training_data[training_data['diagnosis']=='M'].iloc[:,0:15].cov())

In [106]:
np.linalg.det(sigma_hat_m)

19723.27120645123

In [107]:
sigma_hat_m.diagonal()

array([4.83251406e+05, 1.80244546e+04, 1.71425537e+03, 7.92821249e+01,
       4.99687724e+01, 4.96625902e+00, 2.33253962e+00, 5.72687305e-01,
       3.00085039e-01, 8.46220743e-02, 4.76165511e-02, 1.09368344e-02,
       5.88573773e-03, 3.24464641e-03, 2.37829604e-03])

In [108]:
malingnant_prior=training_data[training_data['diagnosis']=='M'].shape[0]/training_data.shape[0]

In [109]:
mu_hat_b=np.array(training_data[training_data['diagnosis']=='B'].iloc[:,0:15].mean())
sigma_hat_b=np.array(training_data[training_data['diagnosis']=='B'].iloc[:,0:15].cov())

In [110]:
sigma_hat_b.shape

(15, 15)

In [111]:
np.linalg.det(sigma_hat_b)

1.8304458896934828e-06

In [112]:
sigma_hat_b.diagonal()

array([3.93448586e+04, 1.18379962e+03, 1.40075464e+02, 2.47387277e+01,
       2.65583990e+01, 1.70909441e+00, 1.36650566e+00, 2.70243150e-01,
       6.55623830e-02, 9.32803276e-02, 2.61349867e-02, 6.33739713e-03,
       2.01105944e-03, 1.86785462e-03, 8.75868974e-04])

In [113]:
benign_prior=training_data[training_data['diagnosis']=='B'].shape[0]/training_data.shape[0]

In [114]:
def mock_test(data):
    inputs=np.array(data.iloc[:,0:15])
    posterior_m=s.multivariate_normal.pdf(inputs,mu_hat_m,sigma_hat_m)*malingnant_prior
    posterior_b=s.multivariate_normal.pdf(inputs,mu_hat_b,sigma_hat_b)*benign_prior
    boolean_mask=posterior_m>posterior_b
    predicted_category=pd.Series(boolean_mask)
    predicted_category.replace(to_replace=[False,True],value=['B','M'],inplace=True)
    return np.array(predicted_category)

In [115]:
cv_results=mock_test(cv_data)

In [116]:
actual_results=np.array(cv_data['diagnosis'])

In [117]:
actual_results

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object)

In [118]:
boolean_mask=cv_results==actual_results

In [119]:
boolean_mask

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [129]:
np.count_nonzero(boolean_mask)

105

In [120]:
cv_accuracy=np.count_nonzero(boolean_mask)/boolean_mask.shape[0]

In [121]:
cv_accuracy

0.9292035398230089

In [130]:
fp=np.count_nonzero(boolean_mask==False)

In [131]:
fp

8

In [ ]:
cv_precision

In [122]:
testing_results=mock_test(testing_data)

In [123]:
testing_results.shape

(58,)

In [124]:
testing_results

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'B',
       'M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

In [125]:
actual_results=np.array(testing_data['diagnosis'])

In [126]:
actual_results

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

In [127]:
testing_accuracy=np.count_nonzero(testing_results==actual_results)/actual_results.shape[0]

In [128]:
testing_accuracy

0.9827586206896551